opencb/opencga

- opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/DBObjectToVariantSourceEntryConverter.java
The previous code assumed that the first element in secondaryAlternates was the primary alternate, thus, the code skipped `alts` if there were just one secondary alternate.
> storage:converters: including secondary allele alternates.

- opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantMongoDBWriter.java
resolves #108.
made indices for:
* `_at.chunkIds`
* `annot.xrefs.id`
* `annot.ct.so`
* `ids`
* `chr`
* `files.fid` + `files.sid`
* `st.maf`
* `st.mgf`
* `chr` + `start` + `end`
> storage: fixed indices creation. resolves #108

- opencga-analysis/src/main/java/org/opencb/opencga/analysis/storage/variant/CatalogVariantDBAdaptor.java
- opencga-storage/opencga-storage-app/src/main/java/org/opencb/opencga/storage/app/cli/OpenCGAStorageMain.java
- opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/adaptors/VariantDBAdaptor.java
- opencga-storage/opencga-storage-hbase/src/main/java/org/opencb/opencga/storage/hbase/variant/VariantHbaseDBAdaptor.java
- opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantMongoDBAdaptor.java
- opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantSourceMongoDBAdaptor.java
fixes #137 
cherry picked from c8e66f7e17805c1eb1962ca1d7b793c061e8a61e
---
Previously, each time a variant was fetched from the DBAdaptor
(DBIterator actually), the inner DBObjectToSamplesConverter made
another query to Mongo to find out the sample names.
In main.statsVariants(), this is a waste because every variant will
share sourceEntry, so the names list will allways be the same. For that,
the adaptor now can be told to fetch the sample names just once at the
beginning.
Conflicts cherry-picking (took ours):
* opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/runner/StringDataWriter.java
* opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/io/VariantDBReader.java
* …
> storage: improved stats performance. (skipping sample names query) fixes #137

- opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/CatalogMongoDBAdaptor.java
- opencga-catalog/src/test/java/org/opencb/opencga/catalog/db/CatalogMongoDBAdaptorTest.java
fixes errors like 'The dotted field `<field.with.dots>` is not valid for storage.'
cherry-picked from b9821ddb1957dbfc93f61d8723f34f659308039e without the change in Job
> catalog: Added compatibility with mongo keynames with dots. (backport)

- opencga-analysis/src/main/java/org/opencb/opencga/analysis/storage/variant/VariantStorage.java
This is done to be able to recognize stats of the same cohorts but from
different files.
> analysis: added filename to stats serialization.

- opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/adaptors/VariantDBAdaptor.java
- opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantMongoDBAdaptor.java
A new option "sort" allows users to choose if they want to sort the results returned from a query by region(s). By default there is no sorting, for the sake of performance.
> New option 'sort' 

- opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/stats/VariantStatisticsManager.java
- opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantMongoDBAdaptor.java
giving "--overwrite-stats" in the storage CLI, the update will do before an
extra pull, removing the cohort stats with the same cid, sid and fid than the
cohort stats it is going to push.
if that option is not present, it will just push the cohort stats, leaving them
repeated if they were already present
> storage: added option to overwrite stats

- opencga-lib/src/main/java/org/opencb/opencga/lib/common/ExceptionUtils.java
- opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/runner/SimpleThreadRunner.java
- opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/VepVariantAnnotator.java
VepVariantAnnotator doesn't log as CellbaseAnnotator anymore, and SimpleThreadRunner now logs exceptions properly: before, it was hiding if the child threads running the tasks died because of unhandled exceptions.
> storage: logger fixes in SimpleThreadRunner and VepVariantAnnotator

- opencga-app/src/main/java/org/opencb/opencga/app/cli/main/OpenCGAMain.java
when "--verbose" is provided, c.cOpt.logLevel is null and it was passed to
storage.
> app: fixed bug when inheriting log level.

- opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/runner/SimpleThreadRunner.java
The logs added help explaining some hangs and restores messages otherwise lost
> storage: bugfix with SimpleThreadRunner child exceptions

- opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/runner/SimpleThreadRunner.java
- opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/VariantStorageManager.java
- opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/runner/SimpleThreadRunnerTest.java
- opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/MongoDBVariantStorageManager.java
Now there is a policy of fast abort.
When a reader, a task, or a writer throws an exception:
* it is logged
* the loops are stopped
* the resources are closed (logging possible nested exceptions)
* the runner throws the original cause of failure.
Previously, if there was an error like an unavailable DB, it hang, logging it indefinitely without exiting the program.
> More SimpleThreadRunner improvements

- opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantSourceMongoDBAdaptor.java
Although the `DBObjectToVariantSourceConverter` is the one that replaces `'.'` with `'£'`, the `VariantSourceMongoDBAdaptor` also queries `DBObjectToVariantSourceConverter.SAMPLES_FIELD`, so it has to do the replacement as well.
> SourceDBAdaptor: fixed bug about samples containing '.'

- opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/DBObjectToVariantSourceEntryConverter.java
- opencga-storage/opencga-storage-mongodb/src/test/java/org/opencb/opencga/storage/mongodb/variant/DBObjectToVariantSourceEntryConverterTest.java
Replacing dots with the pound symbol when converting *VariantSourceEntry.attributes*. Also requires https://github.com/opencb/biodata/pull/85.
> Replacing dots in VariantSourceEntry attributes map

- opencga-app/app/clients/python/pyCGA/RestExecutor.py
This field holds a triple (method, url, post data) of the last REST invocation attempt. This will make debugging and integration much easier.
Closes #426 .
> Added last_invocation field to WS

- opencga-client/src/main/python/pyCGA/Utils/decorators.py
- opencga-client/src/main/python/pyCGA/commons.py
- Fixed a bug when if the configuration provided is a file, its path and not its content is stored in ".opencga" configuration folder.
- Fixed username input, quotes are not longer needed.
- Response id is no longer stored due to the lack of it in some OpenCGA responses.
> pyCGA - Login decorator now creates proper config files

- opencga-client/src/main/python/pyCGA/opencgarestclients.py
- opencga-client/src/main/python/pyCGA/retry.py
- opencga-client/src/main/python/setup.py
Adds a parameter to the pyCGA client to not retry on certain error messages.
> pyCGA: dont retry on certain exceptions

- opencga-client/src/main/python/requirements.txt
while testing out the python client  I noticed that pyyaml was not included in requirements.txt.
> client: add pyyaml to python client requirements.txt

- opencga-catalog/src/main/java/org/opencb/opencga/catalog/utils/UUIDUtils.java
- opencga-catalog/src/test/java/org/opencb/opencga/catalog/utils/UUIDUtilsTest.java
We were having some problems with UUIDUtils.generateOpenCGAUUID not passing some tests due to invalid parsing of binary number strings, so we changed the string conversion ping-pong for simpler bit handling functions; care was taken not to introduce bugs due to Java lack of unsigned types.
> fixed UUIDUtils so it passes the tests

- README.md
Minor update to the README that changes some of the links from HTTP to HTTPS, and means that you're less likely to download Maven (for example) over an HTTP connection.
Please shout if this should be PR'd into a different branch.
> Update README with HTTPS based URLs. Closes issue #941

- .gitignore
- opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/MongoDBAdaptorFactory.java
This change compliments the changes made in https://github.com/opencb/java-common-libs/pull/39. The `sslEnabled` configuration is now picked up from config to allow SSL connections to MongoDB.
To enable SSL for the catalog, configuration such as the following would be required:
``` yaml
catalog:
offset: 0
database:
hosts:
- some.mongo.server.example.com:27017
user: yourUserName
password: yourSuperSecurePassword
options:
authenticationDatabase: admin
connectionsPerHost: 20
sslEnabled: true
```
> Add sslEnabled support to the MongoDBAdapterFactory

- opencga-app/app/scripts/azure/arm/hdinsight/azuredeploy.json
uniquestring function should not have included the prefix. This should be joined with the unique string.
@lawrencegripper - as discussed - can you review and merge.
> Hdinsight cluster name must start with a letter

- opencga-app/app/scripts/azure/arm/hdinsight-storage/azuredeploy.json
Should not get a new storage account each time deployed, just needs to depend on resource group name.
Closes #1025
> Remove reliance for deployment name for storage account.

- opencga-app/app/scripts/docker/opencga-app/Dockerfile
- opencga-app/app/scripts/docker/opencga-daemon/Dockerfile
- opencga-app/app/scripts/docker/opencga/Dockerfile
This PR fixes a number of issues we uncovered yesterday:
- Scripts use '/bin/bash/' which wasn't present in our alpine images
- 'opencga-env.sh' wasn't run prior to starting opencga which caused issues
- 'opencga-env.sh' requires 'BASEDIR' to be set otherwise it doesn't update environment variables as expected
Todo:
Current this builds the images but I need to test them.
> Fixes from debugging docker deployments

- opencga-app/app/scripts/azure/arm/azuredeploy.json
- opencga-app/app/scripts/docker/opencga-init/setup.sh
The Azure Batch service does not like ```--mount``` so switched for ```-v```.
Also the batch mounts reference a ```variants``` directory which needs to be created as part of opencga-init.
> Update volume mounts for batch

- Jenkinsfile
- opencga-app/app/scripts/docker/build-all.sh
- opencga-storage/opencga-storage-hadoop/pom.xml
As discussed, the best way to proceed should be to take the version HDP-2.6.5.3007-2 from the Hortonworks repositories.
- https://github.com/hortonworks/hadoop-release/tree/HDP-2.6.5.3007-2-tag
- http://repo.hortonworks.com/content/repositories/releases/org/apache/hadoop/hadoop-common/2.7.3.2.6.5.3007-2/
- http://repo.hortonworks.com/content/repositories/releases/org/apache/hadoop/hadoop-azure/2.7.3.2.6.5.3007-2/
```
$ jar -tf opencga-storage-hadoop-core-1.4.0-rc3-dev-jar-with-dependencies.jar  | grep StreamCapabi
org/apache/hadoop/fs/StreamCapabilities$StreamCapability.class
org/apache/hadoop/fs/StreamCapabilitiesPolicy.class
org/apache/hadoop/fs/StreamCapabilities.class
$ jar -tf opencga-storage-hadoop-core-1.4.0-rc3-dev-jar-with-dependencies.jar  | grep AzureBlob …
```
> Upgrade HDP-2.6.5 version to HDP-2.6.5.3007-2. Fix Hadoop for Datalake Gen2

- opencga-app/app/scripts/azure/arm/scripts/wait_config.sh
- opencga-app/app/scripts/azure/arm/webservers/azuredeploy.json
This PR aims to address the short term needs of issue #1082.
Notes:
- Only checks `conf` directory
- Waits `5s` after conf directory discovered as a buffer to allow `init-scripts` to run on Daemon - this is a purely huerstic measurement and isn't reliable.
- Is only a temporary fix
- No exit, after 300 iterations the script will try and run the docker containers anyway
- Leaks script level details into the ARM template i.e. the path of the mounts `/media/primarynfs/conf`. If someone changed the script it would break this check.
- WIP: until deployment tested
> Added runcmd to wait on configuration directories being available

- opencga-app/app/scripts/azure/arm/mongodb/azuredeploy.json
Changed the `storageAccountType` to default to SSD disks for the MongoDB cluster, resolving #1029
> Changed default storage to SSD for MongoDB

- opencga-app/app/scripts/azure/arm/azurebatch/azuredeploy.json
Tried few ways to ensure minimum of one node in the batch pool. Then no need to wait 15mins + for nodes to spin up.
Ended up modifying formula. Feels hacky, @lawrencegripper thoughts?
Could parameterise it.
> Ensure always 1 VM in batch pool

- opencga-app/app/scripts/azure/terraform/.dockerignore
- opencga-app/app/scripts/azure/terraform/Dockerfile
- opencga-app/app/scripts/azure/terraform/arm/azuredeploy.json
- opencga-app/app/scripts/azure/terraform/arm/azuredeploy.parameters.json
- opencga-app/app/scripts/azure/terraform/azurebatch/batch.tf
- opencga-app/app/scripts/azure/terraform/azurefiles/main.tf
- opencga-app/app/scripts/azure/terraform/daemonvm/daemonvm.tf
- opencga-app/app/scripts/azure/terraform/entrypoint.sh
- opencga-app/app/scripts/azure/terraform/hdinsight/armwrapper.tf
- opencga-app/app/scripts/azure/terraform/main.tf
- opencga-app/app/scripts/azure/terraform/mongo/mongo.tf
- opencga-app/app/scripts/azure/terraform/network.tf
- opencga-app/app/scripts/azure/terraform/webservers/webservers.tf
Add a simple terraform template that uses ACI to deploy a `terraform` templates that will actually deploy the OpenCGA solution into Azure. This "trick" is needed to allow us to deploy it to the Azure marketplace. This branch is experimental and we're not sure if we'll be able to get all the functionality we need.
05/02/2019 - Status: currently deploying but as the `terraform` tries to spin up new resource groups which is outside the scope of the managed service identity we are using we get 403s. We'll need to condense the solution down to a single resource group to be able to get around this as you cannot assign subscription level MSI scope via an ARM template defined MSI.
06/02/2019 - Status: Modified Terraform and ARM templates to support a single resource group deployment which appears …
> Add an ARM template to deploy Terraform

- opencga-app/app/scripts/azure/arm/armvalconfig.json
- opencga-app/app/scripts/azure/arm/azuredeploy.json
- opencga-app/app/scripts/azure/arm/mongodb/azuredeploy.json
- opencga-app/app/scripts/azure/arm/solr/azuredeploy.json
- opencga-app/app/scripts/azure/arm/solr/solr-setup.sh
Fixes #1186 #1183 and changed Mongo DB data disk to SSD.
Deployed, tested as far as docker logs for solr and data location.
One thing to note is I have used StandardSSD_LRS wich is up to 500 iops and 60MiB/s for a 1 TB disk
We could change VM to 'Es' and a Premium SSD which is up to 5000 iops and 200MiB/s for a 1TB disk.
Larger disk sizes get higher performance. Thoughts?
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disks-types
> Change SOLR disk to SSD and set heap size

- opencga-app/app/scripts/azure/README.md
Very small fix. There's a typo in the README that suggest you use `--it` rather than the correct `-it` flags with `docker exec`
> Fix Docker Exec Typo in README.md

- opencga-app/app/scripts/docker/opencga-app/Dockerfile
This fixes an issue where Tomcat versions are updated and the download link is no longer valid causing the docker build to fail.
> Move tomcat download url

- opencga-app/app/scripts/azure/arm/README.md
Multiple resource group deployments are not currently supported in the portal. CLI is the preferred way to deploy.
> Remove portal button

- opencga-client/src/main/R/R/OpencgaR-methods.R
- opencga-client/src/main/R/R/commons.R
- Add responses and results instead of response and result to support new DataResponse and DataResult data models.
> client: change response and result for responses and results, #1375

- opencga-app/app/misc/clients/js_client_generator.py
- each client is now exposed as an ES Module
- Fix `import` path of `opencga-parent-class.js`
> Update JavaScript OpenCGA Clients generator

- opencga-client/src/main/python/pyopencga/rest_response.py
Addresses #1452
- Fixed print_results for RestResponse when the query yields no results
> Fixed print_results for RestResponse in Python client

- opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/MongoDBAdaptorFactory.java
In the GeL environment, `getPingResponseTime()` always returns NULL. This is fine but it also puts a really big stacktrace in the logs everytime `/health` or `/status` is called which is often.
For now, I've just commented out this check.
```
26-Apr-2021 15:27:17.935 INFO [http-nio-8080-exec-19] com.microsoft.graph.logger.DefaultLogger.logDebug Deserializing type GroupCollectionResponse
java.net.UnknownHostException: bio-uat-opencgainternal-mongodb-01:27017: invalid IPv6 address
at java.net.InetAddress.getAllByName(InetAddress.java:1170)
at java.net.InetAddress.getAllByName(InetAddress.java:1127)
at java.net.InetAddress.getByName(InetAddress.java:1077)
at org.opencb.opencga.catalog.db.mongodb.MongoDBAdaptorFactory.getPingResponseTime(MongoDBAdaptorFactory.java:277)
at …
```
> temporarily disable checking ping time of mongo servers

- opencga-analysis/pom.xml
- opencga-app/pom.xml
- opencga-catalog/pom.xml
- opencga-client/pom.xml
- opencga-core/pom.xml
- opencga-server/pom.xml
- opencga-storage/opencga-storage-app/pom.xml
- opencga-storage/opencga-storage-benchmark/pom.xml
- opencga-storage/opencga-storage-core/pom.xml
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/pom.xml
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-deps/pom.xml
- opencga-storage/opencga-storage-hadoop/pom.xml
- opencga-storage/opencga-storage-mongodb/pom.xml
- opencga-storage/opencga-storage-server/pom.xml
- opencga-storage/pom.xml
- opencga-test/pom.xml
- pom.xml
https://logging.apache.org/log4j/2.x/
Upgrade log4j library to latest version - v2.17.1
> Release 1.3.18. upgrade log4j to 2.17

- opencga-catalog/pom.xml
reverse change in version microsoft-graph: restore prior version (1.4.0)
Reason: In despite of successful login authentication query, there were exception errors and also observed that logger JSON output stopped streaming to stdout/stderr
com.microsoft.aad.adal4j.AuthenticationException: {"error":"invalid_grant","error_uri":"https:\/\/login.microsoftonline.com\/error?code=9002313"}
> reverse change in version microsoft-graph: restore prior version (1.4.0)

- opencga-catalog/src/main/java/org/opencb/opencga/catalog/auth/authentication/LDAPAuthenticationManager.java
> TASK-2588 - NullPointerExceptions when LDAP is set not to use the serviceAccount user credential (authUserId, authPassword)

- opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/metadata/CatalogStorageMetadataSynchronizer.java
- opencga-analysis/src/test/java/org/opencb/opencga/analysis/variant/manager/operations/VariantFileIndexerOperationManagerTest.java
- opencga-client/src/main/java/org/opencb/opencga/client/rest/AbstractParentClient.java
- opencga-core/src/main/java/org/opencb/opencga/core/common/UriUtils.java
- opencga-core/src/test/java/org/opencb/opencga/core/common/UriUtilsTest.java
- opencga-storage/opencga-storage-app/src/main/java/org/opencb/opencga/storage/app/cli/client/executors/VariantCommandExecutor.java
- opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/VariantStoragePipeline.java
TASK-2530 - Error working with files with URL codes (e.g. %A3) in their name
> TASK-2530 - Error working with files with URL codes (e.g. %A3) in their name

- opencga-analysis/src/main/java/org/opencb/opencga/analysis/alignment/AlignmentStorageManager.java
- opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/manager/operations/VariantAnnotationOperationManager.java
- opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/manager/operations/VariantFileIndexerOperationManager.java
- opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/metadata/CatalogStorageMetadataSynchronizer.java
- opencga-app/src/main/java/org/opencb/opencga/app/migrations/v2_1_0/storage/AddCellbaseConfigurationToProject.java
- opencga-app/src/main/java/org/opencb/opencga/app/migrations/v2_6_0/storage/AddCellbaseDataRelease.java
- opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/variant/VariantStorageEngineSVTest.java
Fix CellBase data release usage
> TASK-3836 - Fix CellBase data release usage

- opencga-app/app/misc/clients/python_client_generator.py
- opencga-client/src/main/python/pyopencga/commons.py
> TASK-2012 - python rest client: inconsistent parameter strings

- misc/newHotfixBranch.sh
- misc/new_hotfix_branch.sh
TASK-3885 - Script to create hotfix branch
> TASK-3885 - Script to create hotfix branch

- opencga-analysis/src/main/java/org/opencb/opencga/analysis/wrappers/exomiser/ExomiserWrapperAnalysisExecutor.java
- opencga-core/src/main/java/org/opencb/opencga/core/config/storage/SampleIndexConfiguration.java
- opencga-storage/opencga-storage-core/src/test/resources/variant-multiallelic.vcf
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/SampleIndexOnlyVariantQueryExecutor.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/core/CategoricalIndexField.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/core/CategoricalMultiValuedIndexField.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/core/FixedSizeIndexSchema.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/core/IndexField.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/core/RangeIndexField.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/core/SingleFieldIndexSchema.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/family/MendelianErrorSampleIndexEntryIterator.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/AbstractSampleIndexEntryFilter.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/FileIndexSchema.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexDBLoader.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexEntryIterator.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexSchema.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexVariantBiConverter.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleVariantIndexEntry.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/VariantTypeIndexCodec.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/index/core/CategoricalIndexFieldTest.java
- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexTest.java
TASK-4794 - Missing "FILTER" field in VCF generated (export step) while running Exomiser
> TASK-4794 - Missing "FILTER" field in VCF generated (export step) while running Exomiser

- opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/VariantStorageEngine.java
TASK-4938 - OpenCGA VariantExport tests sometimes throw a ConcurrentModificationException
> TASK-4938 - OpenCGA VariantExport tests sometimes throw a ConcurrentModificationException

- opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/pom.xml
TASK-5394 - NoClassDefFoundError: org/apache/logging/log4j/spi/AbstractLoggerAdapter
> TASK-5394 - NoClassDefFoundError: org/apache/logging/log4j/spi/AbstractLoggerAdapter

- .github/workflows/scripts/get_same_branch.sh
- .github/workflows/test-analysis.yml
- opencga-server/pom.xml
- pom.xml
TASK-5475 - The version of Java (11.0.21) used to run our analysis is deprecated, and SonarCloud no longer supports it.
> TASK-5475 - The version of Java (11.0.21) used to run our analysis is deprecated, and SonarCloud no longer supports it.

- opencga-app/app/misc/scripts/hadoop-ssh.sh
TASK-5452 - "Wrong number of arguments" launching MR operation
> TASK-5452 - "Wrong number of arguments" launching MR operation

- opencga-app/src/main/java/org/opencb/opencga/app/cli/CommandExecutor.java
- opencga-app/src/main/java/org/opencb/opencga/app/cli/main/executors/SamplesCommandExecutor.java
- opencga-server/src/main/java/org/opencb/opencga/server/generator/models/RestParameter.java
TASK-5556 - OpenCGA CLI --json-data-model does not produce parseable JSONS
> TASK-5556 - OpenCGA CLI --json-data-model does not produce parseable JSONS

- .github/workflows/release.yml
TASK-6185 - Modify release workflows for OpenCB and Enterprise to include all 4 Hadoop flavors
> TASK-6185 - Modify release workflows for OpenCB and Enterprise to include all 4 Hadoop flavors

- .github/workflows/pull-request-approved.yml
- opencga-app/app/misc/clients/javascript_client_generator.py
- opencga-client/src/main/javascript/ClinicalAnalysis.js
- opencga-client/src/main/javascript/File.js
- opencga-client/src/main/javascript/GA4GH.js
- opencga-client/src/main/javascript/Job.js
- opencga-client/src/main/javascript/Project.js
- opencga-client/src/main/javascript/Study.js
- opencga-client/src/main/javascript/User.js
TASK-6636 - Job Kill method in JavaScript client of OpenCGA sends the params as POST body data
[https://app.clickup.com/t/36631768/TASK-6636](https://app.clickup.com/t/36631768/TASK-6636)
> TASK-6636 - Job Kill method in JavaScript client of OpenCGA sends the params as POST body data

- opencga-app/src/main/java/org/opencb/opencga/app/cli/main/custom/CustomUsersCommandExecutor.java
- opencga-app/src/main/java/org/opencb/opencga/app/cli/main/processors/CommandProcessor.java
- pom.xml
TASK-6992 - Error with token in the CLI
> TASK-6992 - Error with token in the CLI

- .github/workflows/pull-request-merged.yml
[TASK-6880 - CI/CD workflow to delete task docker images on merge fails](https://app.clickup.com/t/36631768/TASK-6880)
> TASK-6880 - CI/CD workflow to delete task docker images on merge fails
