opencb/opencga

opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/VariantStorageManager.java

requires https://github.com/opencb/biodata/pull/35 to be merged first.

updated to use exac aggregation stats parsing

---

opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/DBObjectToVariantConverter.java
opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/DBObjectToVariantSourceEntryConverter.java
opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/DBObjectToVariantStatsConverter.java
opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantMongoDBAdaptor.java
opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantMongoDBWriter.java
opencga-storage/opencga-storage-mongodb/src/test/java/org/opencb/opencga/storage/mongodb/variant/DBObjectToVariantConverterTest.java
opencga-storage/opencga-storage-mongodb/src/test/java/org/opencb/opencga/storage/mongodb/variant/DBObjectToVariantSourceEntryConverterTest.java

from this: 
```
{
files: [
{
sid:
fid:
st: [
{
cid:
}, ...
]
}, ...
}
}
```
to this: 
```
{
files: [
{
sid:
fid:
}, ...
],
st: [
{
sid:
fid:
cid:
}, ...
]
}
```

moving out the stats array in the mongo schema

---

opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/DBObjectToVariantSourceConverter.java
opencga-storage/opencga-storage-mongodb/src/test/java/org/opencb/opencga/storage/mongodb/variant/DBObjectToVariantSourceConverterTest.java

storage:mongo: replaced dots in header tags. resolves #51

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/storage/variant/CatalogVariantDBAdaptor.java
opencga-storage/opencga-storage-app/src/main/java/org/opencb/opencga/storage/app/cli/OpenCGAStorageMain.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/runner/StringDataWriter.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/VariantJsonTransformTask.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/VariantStorageManager.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/adaptors/VariantDBAdaptor.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/adaptors/VariantDBIterator.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/io/VariantDBReader.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/stats/VariantStatisticsManager.java
opencga-storage/opencga-storage-hbase/src/main/java/org/opencb/opencga/storage/hbase/variant/VariantHbaseDBAdaptor.java
opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantMongoDBAdaptor.java
opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantMongoDBIterator.java
opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantSourceMongoDBAdaptor.java

The stats are now implemented in multithread.
The bottleneck is in the converters at the retrieval from mongo, although some work has also been done there.

storage: Improved stats calculation performance

---

opencga-storage/opencga-storage-app/src/main/java/org/opencb/opencga/storage/app/cli/OpenCGAStorageMain.java
opencga-storage/opencga-storage-app/src/main/java/org/opencb/opencga/storage/app/cli/OptionsParser.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/VariantAnnotationManager.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/VepVariantAnnotator.java
pom.xml

this annotator can only be used with the `--load` option, as it assumes the annotation file has been created externally.
resolves #78

added VEP annotation loader

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/CatalogMongoDBAdaptor.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/CatalogManagerTest.java

catalog: fixed wrong exception about lastActivity. resolves #71

---

opencga-app/src/main/java/org/opencb/opencga/app/cli/main/OptionsParser.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/beans/Study.java
opencga-storage/opencga-storage-app/src/main/java/org/opencb/opencga/storage/app/cli/OptionsParser.java

Now the default study type is COLLECTION

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/CatalogSampleAnnotationsLoader.java

Now in hotfix/0.5, it is allowed to load a ped file after indexing a vcf (#64).
Already tested.

back ported #64 into hotfix/0.5

---

opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/stats/VariantStatisticsCalculator.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/stats/VariantStatisticsManager.java

storage: now source stats are written properly.

---

opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantMongoDBWriter.java

storage: mongo indices are now created in background. fixes #108

---

opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/VariantStorageManager.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/stats/VariantStatisticsManager.java

fixes #137
just added 
```
options.put(VariantDBAdaptor.STUDIES, Collections.singletonList(variantSource.getStudyId()));
options.put(VariantDBAdaptor.FILES, Collections.singletonList(variantSource.getFileId()));
```

storage: improved variant querying in stats. fixes #137

---

opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantMongoDBAdaptor.java

Stats updating is done in 2 steps for each variant. 
Having a list `cohorts` of cohort stats, each one with fileId, studyId, cohortId and stats-related values:
* remove from mongo all already present cohort stats that match the 3 ids of any element in `cohorts`
* push `cohorts` 
This way makes that no repeated cohort stats will be present in mongo, and old values can be updated, as well as loading stats in several steps.

storage: fixed bug of non-related cohort stats being overwritten.

---

opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/runner/SimpleThreadRunner.java

Before, when child threads failed, the main thread may cause concurrent issues at closing resources, because the children didn't finish immediately.
Now, the main thread waits (for a maximum of 30 seconds) so that every child is terminated. Tests show that less than a second is enough to finish everything orderly.

storage: fixed simpleThreadRunner gzip hang

---

opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantSourceMongoDBAdaptor.java

Before, when the samples of a fileId were asked, the condition to retrieve them
from the "files" collection was that the number of files wasn't the same. This
is wrong.
The fix is: when the samples of a fileId are asked, look up those fileIds in
the cache, and if there is anyone missing, empty the cache, and dump the
samplenames from the "files" collection.

storage: fixed bug with VariantSourceMongoDBAdaptor sample cache.

---

opencga-app/src/main/java/org/opencb/opencga/app/cli/main/OpencgaCliOptionsParser.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/main/executors/ProjectsCommandExecutor.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/main/executors/SamplesCommandExecutor.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/main/executors/StudiesCommandExecutor.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/main/options/ProjectCommandOptions.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/main/options/SampleCommandOptions.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/main/options/StudyCommandOptions.java
opencga-client/src/main/java/org/opencb/opencga/client/rest/AbstractParentClient.java
opencga-client/src/main/java/org/opencb/opencga/client/rest/SampleClient.java
opencga-client/src/main/java/org/opencb/opencga/client/rest/StudyClient.java

Executor and Options of Projects finished..Building executor and options of samples. Bug fixes functions of clients. #320. Create new functions for acl.

Executor and Options of Projects finished.

---

opencga-app/app/clients/python/pyCGA/RestExecutor.py

Fix pyCGA error messages from server not reported

---

opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/GenomeHelper.java

Fix for https://github.com/opencb/opencga/issues/528

#528 fix - OpenCGA fails to parse NC_007605 contigs.

---

opencga-client/src/main/python/pyCGA/commons.py
opencga-client/src/main/python/pyCGA/opencgarestclients.py

- added a simple constructor for OpenCGAClient that only takes url, username and password:
`c = OpenCGAClient.basic('localhost:8080/opencga', 'myuser', 'mypass')`
- added automatic conversion to string of query ids. 
Now we can do things like `c.files.update(10, data={...})` where before we needed `c.files.update(str(10), data={...})`

Two minor enhancements to pyCGA:

---

opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Families/FamiliesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/MetaTests/MetaTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/OpenCGACompleteLifeCycle/OpenCGACompleteLifeCycleTest/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Samples/SamplesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/SuiteSetUp/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/SuiteTearDown/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/VariableSet/VariableSetTests/content.txt

Added more tests, bug fixes modifications and some refactoring

Release 1.1.0

---

opencga-client/src/main/python/pyCGA/opencgarestclients.py

- Addition of "families" and "meta" methods
- Refactoring of acl methods

Fix pycga client

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/session/JwtSessionManager.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/session/JwtSessionManagerTest.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/OpenCGAWSServer.java
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Individuals/IndividualsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/JWT/JWTTests/content.txt

@pfurio  could you please have a look and merge this tiny item to make things convenient for user in swagger ?

REST: put check to ignore if only Bearer is provided

---

opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Cohorts/CohortsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Files/FilesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Individuals/IndividualsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Jobs/JobsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/OpenCGACompleteLifeCycle/OpenCGACompleteLifeCycleTest/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Panels/PanelsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Panels/properties.xml
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Projects/ProjectTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Samples/SamplesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Studies/StudiesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/SuiteSetUp/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Users/UserTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/VariableSet/VariableSetTests/content.txt

@pfurio could you please merge this ? Thanks

Release 1.2.0 test

---

opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/JWT/JWTTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/OpenCGACompleteLifeCycle/OpenCGACompleteLifeCycleTest/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Samples/SamplesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Users/UserTests/content.txt

@pfurio please merge these minor changes.

Test: adopted tests with error code changes and added new

---

checkstyle.xml
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/CohortManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/FamilyManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/FileManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/IndividualManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/JobManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/ProjectManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/ResourceManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/SampleManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/StudyManager.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/ClinicalAnalysisWSServer.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/CohortWSServer.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/FamilyWSServer.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/FileWSServer.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/IndividualWSServer.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/JobWSServer.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/ProjectWSServer.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/SampleWSServer.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/StudyWSServer.java

@pfurio please merge before further changes.

REST: changes for accepting list of ids instead of single item

---

opencga-server/src/main/java/org/opencb/opencga/server/rest/CohortWSServer.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/FamilyWSServer.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/IndividualWSServer.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/SampleWSServer.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/StudyWSServer.java

@pfurio Please review and if seems ok, merge. Thanks

REST: adopted REST api for accepting list of Ids

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/IndividualManager.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/alignment/local/LocalAlignmentDBAdaptor.java
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Cohorts/CohortsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Individuals/IndividualsTests/content.txt

CheckStyle fix causing development failure 

---

opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Cohorts/CohortsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Families/FamiliesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Files/FilesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Individuals/IndividualsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Jobs/JobsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Projects/ProjectTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Samples/SamplesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/SuiteTearDown/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/SuiteTearDown/properties.xml
opencga-test/fitnesse/FitNesseRoot/OpenCga/properties.xml

More Tests for 1.3

---

opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Cohorts/CohortsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Studies/StudiesTests/content.txt

Anonymous Test for Study

---

opencga-client/src/main/R/R/OpencgaR-methods.R
opencga-client/src/main/R/R/deprecated/OpencgaFunctions.R
opencga-client/src/main/R/R/deprecated/opencgaConfig.R
opencga-client/src/main/R/man/initOpencgaR.Rd
opencga-client/src/main/R/man/opencgaHelp.Rd
opencga-client/src/main/R/man/opencgaLogin.Rd
opencga-client/src/main/R/man/opencgaReadConfig.Rd
opencga-client/src/main/R/vignettes/opencgaR.Rmd

Hi All
Here is my suggested outline for the opencgaR vignette,  and some documentation fixes. I noticed that reading the config from files or a list although documented in the package is not yet enabled, resulting in some errors in R CMD check 
#724

added vignette backbone and some documentation fixes

---

opencga-server/src/main/java/org/opencb/opencga/server/rest/analysis/AlignmentAnalysisWSService.java

@pfurio please have a loot and merge if fine. Thanks

Minor Validations in Alignment WS

---

opencga-client/src/main/python/pyCGA/opencgarestclients.py
opencga-client/src/main/python/setup.py

- Compatibility changes
- Anonymous user support

Adapted pyCGA for opencga 1.3.0

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/StudyManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/stats/solr/CatalogSolrQueryParser.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/stats/solr/FileSolrModel.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/stats/solr/converters/CatalogFileToSolrFileConverter.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/stats/solr/converters/CatalogSampleToSolrSampleConverter.java
opencga-catalog/src/main/resources/solr/file-managed-schema.xml
opencga-server/src/main/java/org/opencb/opencga/server/rest/FileWSServer.java

@pfurio could you please have a look and merge ? Thanks

Solr stats

---

opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Cohorts/CohortsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Families/FamiliesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Files/FilesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Individuals/IndividualsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/JWT/JWTTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Jobs/JobsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/MetaTests/MetaTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/OpenCGACompleteLifeCycle/OpenCGACompleteLifeCycleTest/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Projects/ProjectTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Samples/SamplesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Studies/StudiesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/SuiteSetUp/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Users/UserTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/VariableSet/VariableSetTests/content.txt

@pfurio  could you please have a look and merge please ? Thanks

Test: replaced deprecated sessionId with set Header

---

opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Cohorts/CohortsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/DiseasePanel/DiseasePanelTests.wiki
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Families/FamiliesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Files/FilesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Individuals/IndividualsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Jobs/JobsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Samples/SamplesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/SuiteSetUp/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Users/UserTests/content.txt

@pfurio  some small changes, typos, could you please have a look and merge? Thanks

Release 1.4.0

---

opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/DiseasePanel/DiseasePanelTests.wiki
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Families/FamiliesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Individuals/IndividualsTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Projects/ProjectTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/Samples/SamplesTests/content.txt
opencga-test/fitnesse/FitNesseRoot/OpenCga/TestsSuits/SuiteSetUp/content.txt

@pfurio could you please have a look and merge ? Thanks

Test: changed Disease Panels to Panels and minor change in incRelease

---

opencga-app/app/scripts/azure/arm/azuredeploy.json
opencga-app/app/scripts/azure/arm/solr/solr-setup.sh
opencga-app/app/scripts/azure/arm/solr/zookeeper/zookeeper-setup.sh
opencga-app/app/scripts/azure/arm/webservers/azuredeploy.json

Issue 965 - Fix Avere issue, Enable Switch between AzureFiles and Avere

---

.vscode/settings.json
opencga-app/app/scripts/azure/arm/avere/mount.py
opencga-app/app/scripts/azure/arm/azurebatch/azuredeploy.json
opencga-app/app/scripts/azure/arm/azurebatch/configurepool.py
opencga-app/app/scripts/azure/arm/azurebatch/pool.json
opencga-app/app/scripts/azure/arm/azuredeploy.json
opencga-app/app/scripts/azure/arm/deploy.sh
opencga-app/app/scripts/azure/arm/hdinsight/azuredeploy.json
opencga-app/app/scripts/azure/arm/vnet/azuredeploy.json

This template creates an auto-scaling Azure Batch Account and node pool which support Container based tasks. 
When there is no work in the queue the pool scales down to 0 machines, this reduces costs but does mean tasks will have a start time of around ~5/8 mins depending on when the auto-scaling rule was last evaluated. 
To work around a limitation in the ARM API the pool creation is handled by an ACI container with a MSI assigned to it. Hopefully this can be removed in future. 
Remaining work:

ARM Template for Azure Batch

---

Jenkinsfile
opencga-app/app/scripts/azure/arm/armvalconfig.json
opencga-app/app/scripts/azure/arm/azurebatch/azuredeploy.json
opencga-app/app/scripts/azure/arm/hdinsight/azuredeploy.json
opencga-app/app/scripts/azure/arm/solr/zookeeper/azuredeploy.json

Related #950 
This adds an ARM validation step, fixes some fixable ARM validation errors and adds an ignore file for those that are false positives

Add ARM Validation step to the CI Build

---

opencga-app/app/scripts/docker/opencga-init/override-yaml.py
opencga-app/app/scripts/docker/opencga/Dockerfile

Added user name to user UID in Docker images. This addresses #1012

Added user name to user UID in Docker images

---

Jenkinsfile
opencga-app/app/scripts/azure/arm/azurebatch/azuredeploy.json

Fixes #1020 
This moves to default ACI to use West Europe when used by Azure Batch

Move ACI location to westeurope default

---

opencga-app/app/scripts/azure/arm/azuredeploy.json
opencga-app/app/scripts/azure/arm/azuredeploy.parameters.json
opencga-app/app/scripts/azure/arm/daemonvm/azuredeploy.json
opencga-app/app/scripts/azure/arm/hdinsight/azuredeploy.json
opencga-app/app/scripts/azure/arm/mongodb/azuredeploy.json
opencga-app/app/scripts/azure/arm/solr/azuredeploy.json
opencga-app/app/scripts/azure/arm/solr/zookeeper/azuredeploy.json
opencga-app/app/scripts/azure/arm/webservers/azuredeploy.json

Issue 1024 Simplify ARM Params

---

pom.xml

Fix IllegalAccessError connecting to Phoenix

---

opencga-app/app/scripts/docker/opencga-daemon/Dockerfile

Docker: add healthcheck in opencga-daemon

---

opencga-app/app/conf/hadoop/hadoop-ssh.sh
opencga-storage/opencga-storage-core/src/main/resources/storage-configuration.yml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/HadoopMRLoadVariantStoragePipeline.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/HadoopVariantStorageEngine.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/HadoopVariantStoragePipeline.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/executors/MRExecutor.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/executors/MRExecutorFactory.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/executors/SshMRExecutor.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/executors/SystemMRExecutor.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/HadoopVariantStorageTest.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/executors/SshMRExecutorTest.java

Implements #1156
Related with #1113 and #1155

WIP: Implement SshMRExecutor.

---

opencga-app/app/scripts/azure/README.md

These provide some guidance to users running through the `Testing` section with an ARM based deployment.

Readme changes noting differences when using ARM deployment.

---

opencga-app/app/scripts/azure/arm/README.md
opencga-app/app/scripts/azure/arm/azuredeploy.json

I've added a way to define bespoke TShirt sizes for the solution. 
What do you think?

Add `customTShirt` sizing for testing and tweaking.

---

opencga-app/app/conf/hadoop/hadoop-ssh.sh
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/executors/SshMRExecutor.java

Fix relocation of jar-with-dependencies path

---

opencga-app/app/scripts/azure/arm/azuredeploy.json
opencga-app/app/scripts/azure/arm/hdinsight/azuredeploy.json

Closes #1185
Configure the `yarn-site` memory settings from ARM.

Add Yarn site parameter to configure memory allocation

---

opencga-app/app/scripts/azure/arm/azuredeploy.json

Move to 4 core boxes for all deployment sizes 

---

opencga-app/app/scripts/azure/arm/azuredeploy.parameters.json

The azuredeploy.parameters.json file had become out of sync with the base template.

Update parameters file for Azure deployments

---

opencga-app/app/scripts/azure/arm/daemonvm/azuredeploy.jsonc

Change OpenCGA rest URL to use https

---

opencga-app/app/scripts/azure/arm/appgw/azuredeploy.json
opencga-app/app/scripts/azure/arm/azurebatch/azuredeploy.json
opencga-app/app/scripts/azure/arm/daemonvm/azuredeploy.jsonc
opencga-app/app/scripts/azure/arm/deploy.sh
opencga-app/app/scripts/azure/arm/loganalytics/azuredeploy.json
opencga-app/app/scripts/azure/arm/webservers/azuredeploy.json

Created a new deployment script with improved artifact handling - can develop without pushing up to github each time.
Fixed a couple of deployment bugs and removed uneccessary OMS solution.

Rework artifacts handling

---

opencga-app/src/main/java/org/opencb/opencga/app/cli/admin/AdminCliOptionsParser.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/admin/executors/CatalogCommandExecutor.java

@pfurio could you please have a look ?

Make catalog secretKey optional 

---

opencga-app/app/cloud/k8s/opencga/base/conf/client-configuration.yml
opencga-app/app/cloud/k8s/opencga/base/conf/configuration.yml
opencga-app/app/cloud/k8s/opencga/base/conf/hadoop/README.md
opencga-app/app/cloud/k8s/opencga/base/conf/hadoop/hadoop-ssh.sh
opencga-app/app/cloud/k8s/opencga/base/conf/log4j.properties
opencga-app/app/cloud/k8s/opencga/base/conf/opencga-env.sh
opencga-app/app/cloud/k8s/opencga/base/conf/storage-configuration.yml
opencga-app/app/cloud/k8s/opencga/base/daemon-deployment.yaml
opencga-app/app/cloud/k8s/opencga/base/fabric8-rbac.yaml
opencga-app/app/cloud/k8s/opencga/base/kustomization.yaml
opencga-app/app/cloud/k8s/opencga/base/namespace.yaml
opencga-app/app/cloud/k8s/opencga/base/pv-claim.yaml
opencga-app/app/cloud/k8s/opencga/base/rest-deployment.yaml
opencga-app/app/cloud/k8s/opencga/base/service.yaml
opencga-app/app/cloud/k8s/opencga/overlays/azure/azure-shared-disk.yaml
opencga-app/app/cloud/k8s/opencga/overlays/azure/kustomization.yaml

K8S Scripts for OpenCGA and AKS with sample Configuration

K8S Scripts 

---

opencga-app/app/misc/clients/python_client_generator.py
opencga-app/app/misc/clients/rest_client_generator.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/admin_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/alignment_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/clinical_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/cohorts_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/families_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/files_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/ga4gh_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/individuals_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/jobs_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/meta_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/panels_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/projects_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/samples_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/studies_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/users_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/variant_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_clients/variant_operations_client.py
opencga-client/src/main/python/pyOpenCGA/pyopencga/rest_response.py

Addresses: #1464
- Improved Python script to create rest clients automatically
- New rest clients created with new script

Implement a code generator python script to create python clients

---

opencga-client/src/main/python/pyopencga/opencga_client.py
opencga-client/src/main/python/pyopencga/rest_clients/_parent_rest_clients.py

Addresses #1452
- Added refresh token to login

pyopencga: Add refresh token to login

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/auth/authentication/LDAPAuthenticationManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/auth/authentication/LDAPUtils.java
opencga-core/src/main/java/org/opencb/opencga/core/config/AuthenticationOrigin.java
opencga-core/src/main/resources/configuration.yml

Adds support for ldaps:// connections to LDAPConfigurationManager. Closes #1257 . Also adds some config options to accommodate variations in the structures of different LDAP installations.

LDAPS support for 1.4.x

---

opencga-client/src/main/python/pyopencga/commons.py

Addresses #1696
- Added delete support

Python client: added delete support

---

opencga-analysis/src/main/R/circos/circos.R

- Expected rearrangement types changed in circos Rscript

Change expected rearrangement types in circos Rscript

---

opencga-client/src/main/python/notebooks/user-training/001-pyopencga_first_steps.ipynb
opencga-client/src/main/python/notebooks/user-training/002-pyopencga_CATALOG.ipynb
opencga-client/src/main/python/notebooks/user-training/003-pyopencga_variant_analysis.ipynb
opencga-client/src/main/python/notebooks/user-training/pyopencga_first_steps_001.ipynb

client: Improve notebook 1, 2 noteboks left created #1716

---

opencga-client/src/main/python/notebooks/user-training/pyopencga_catalog.ipynb
opencga-client/src/main/python/notebooks/user-training/pyopencga_first_steps.ipynb
opencga-client/src/main/python/notebooks/user-training/pyopencga_variant_analysis.ipynb
opencga-client/src/main/python/notebooks/user-training/pyopencga_variant_query.ipynb

Improvements in the notebooks schema

client: improving notebooks structure #1716

---

opencga-client/src/main/python/notebooks/user-training/pyopencga_catalog.ipynb
opencga-client/src/main/python/notebooks/user-training/pyopencga_variant_query.ipynb

client-improved: pyopencga_variant_query.ipynb #1716

---

opencga-client/src/main/python/pyopencga/rest_response.py
opencga-client/src/main/python/setup.py

- Added to_data_frame method to get a pandas DataFrame from rest response

Added to_data_frame method for rest responses

---

opencga-client/src/main/python/pyopencga/opencga_client.py
opencga-client/src/main/python/requirements.txt

Fix wait_for_job method in client

---

opencga-client/src/main/python/pyopencga/rest_response.py

- Added customisable title when printing results in method print_results()

Added customisable title to print results

---

opencga-client/src/main/python/notebooks/admin-training/pyopencga_admin.ipynb

- Add folder admin-training
- Create notebook and first draft of the scheleton

client: create structure of admin notebook #1716

---

opencga-client/src/main/python/pyopencga/opencga_client.py

-     Wait_for_job method is fixed

Fix wait_for_job functionality

---

opencga-app/pom.xml
opencga-app/src/main/java/org/opencb/opencga/app/cli/admin/executors/ServerCommandExecutor.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/main/executors/analysis/AlignmentCommandExecutor.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/main/executors/analysis/VariantCommandExecutor.java
opencga-storage/opencga-storage-app/src/main/java/org/opencb/opencga/storage/app/cli/server/executors/GrpcCommandExecutor.java
pom.xml

update grpc-netty 1.44.1 for vulnerability scan

update grpc-netty dependency version

---

opencga-client/src/main/python/pyopencga/opencga_client.py

- Wait_for_job method is fixed

Fix wait_for_job status functionality

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/CohortMongoDBAdaptor.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/SampleMongoDBAdaptor.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/ClinicalAnalysisManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/CohortManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/FamilyManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/IndividualManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/SampleManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/utils/ParamUtils.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/SampleManagerTest.java

TASK-2047: Change ids to empty strings should not be allowed

---

opencga-core/src/main/java/org/opencb/opencga/core/models/family/FamilyCreateParams.java
opencga-core/src/main/java/org/opencb/opencga/core/models/individual/IndividualCreateParams.java

TASK-2063: Can create individual and family without id

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/ProjectManager.java
opencga-core/src/main/java/org/opencb/opencga/core/api/ParamConstants.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/query/executors/BreakendVariantQueryExecutor.java
opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/variant/VariantStorageEngineBNDTest.java
opencga-storage/opencga-storage-core/src/test/resources/variant-test-bnd.vcf

TASK-2034 - Unable to find mate of variant

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/rga/RgaEngine.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/rga/RgaQueryParser.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/rga/iterators/RgaIterator.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/rga/iterators/SolrNativeIterator.java
opencga-analysis/src/test/java/org/opencb/opencga/analysis/rga/RgaManagerTest.java
opencga-core/src/main/java/org/opencb/opencga/core/models/analysis/knockout/KnockoutByGeneSummary.java

TASK-2111: "and" queries are not working in RGA

---

opencga-catalog/src/test/java/org/opencb/opencga/catalog/utils/InterpretationUtilsTest.java
opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/converters/DocumentToVariantAnnotationConverter.java

Update according to biodata changes.

TASK-2041 Add HGVS data to consequenceTypes

---

opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/converters/DocumentToVariantAnnotationConverter.java

TASK-2041 - Add HGVS data to consequenceTypes

---

opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/adaptors/VariantQuery.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/query/VariantQueryParser.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexQueryParser.java

TASK-2112 - Variant export sample will include only variants with clinical information

---

opencga-master/src/main/java/org/opencb/opencga/master/monitor/daemons/ExecutionDaemon.java
opencga-master/src/test/java/org/opencb/opencga/master/monitor/daemons/ExecutionDaemonTest.java

TASK-2138 - Error creating opencga-internal.sh command line from nested job params

---

opencga-analysis/src/test/resources/exomiser/output.yml
opencga-app/app/analysis/exomiser/output.yml

TASK-1943 Fix interpretation-exomiser analysis: too many variants

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/rga/RgaEngine.java

TASK-2111 - 'and' queries not working in RGA

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/manager/VariantCatalogQueryUtils.java
opencga-analysis/src/test/java/org/opencb/opencga/analysis/variant/manager/VariantCatalogQueryUtilsTest.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/adaptors/VariantQueryParam.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/query/VariantQueryParser.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/query/VariantQueryUtils.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/query/executors/DBAdaptorVariantQueryExecutor.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/query/projection/VariantQueryProjectionParser.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/search/VariantSearchUtils.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/SampleIndexMendelianErrorQueryExecutor.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/SampleIndexOnlyVariantQueryExecutor.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/family/GenotypeCodec.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/query/SampleIndexQuery.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/query/SingleSampleIndexQuery.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/AbstractSampleIndexEntryFilter.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexDBAdaptor.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexQueryParser.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/index/family/FamilyIndexTest.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexEntryFilterTest.java
opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/MongoDBVariantStorageEngine.java

TASK-2195 - Filter by DeNovo Strict variants

---

opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/VariantStorageEngine.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/query/executors/NoOpVariantQueryExecutor.java
opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/variant/adaptors/VariantDBAdaptorTest.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/HadoopVariantStorageEngine.java

TASK-2224 - Variant Query Timeout with impossible cohort stats filter values

---

opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/metadata/VariantStorageMetadataManager.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/adaptors/VariantQuery.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/SampleIndexOnlyVariantQueryExecutor.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/family/GenotypeCodec.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/family/MendelianErrorSampleIndexEntryIterator.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/query/SampleIndexQuery.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/query/SingleSampleIndexQuery.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexDBAdaptor.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexEntryIterator.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexQueryParser.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleVariantIndexEntry.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/index/family/FamilyIndexTest.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexEntryFilterTest.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexTest.java

TASK-2230 - Allow variant family export directly from secondary sample index

---

opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/io/VariantTpedWriter.java

TASK-2215 Fix family quality control (relatedness) when saving in OpenCGA catalog

---

opencga-app/src/main/java/org/opencb/opencga/app/migrations/v2_4_10/catalog/AddMissingEndDateOnFinishedJobs.java
opencga-master/src/main/java/org/opencb/opencga/master/monitor/daemons/ExecutionDaemon.java

TASK-2237 - Incorrect runtime value when the job fails with error

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/rga/IndividualRgaConverter.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/rga/RgaManager.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/rga/RgaUtils.java

TASK-2277: Empty results in RGA variant query

---

opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/prune/VariantPruneManager.java

TASK-2263 - Unable to variant-prune after variant-study-delete

---

opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/prune/VariantPruneDriver.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/prune/VariantPruneManagerTest.java

TASK-2285 - Error running variant-prune - "cohort ALL not found in variant"

---

opencga-analysis/src/test/java/org/opencb/opencga/analysis/variant/VariantAnalysisTest.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/utils/AbstractHBaseDriver.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/mr/PhoenixVariantTableInputFormat.java

TASK-2276 - TPED exports more samples than expected when using PhoenixVariantTableInputFormat

---

opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/metadata/VariantStorageMetadataManager.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/metadata/adaptors/VariantStorageMetadataDBAdaptorFactory.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/utils/HBaseManager.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/converters/HBaseToVariantConverter.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/metadata/AbstractHBaseDBAdaptor.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/metadata/HBaseFileMetadataDBAdaptor.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/metadata/HBaseVariantStorageMetadataDBAdaptorFactory.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/mr/CustomPhoenixInputFormat.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/mr/HBaseVariantTableInputFormat.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/mr/PhoenixVariantTableInputFormat.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/mr/VariantsTableMapReduceHelper.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/pending/DiscoverPendingVariantsDriver.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/VariantHbaseTestUtils.java

TASK-2381 - Multiple HBase connections opened at MapReduce

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/tools/OpenCgaTool.java
opencga-core/src/main/java/org/opencb/opencga/core/tools/result/ExecutionResultManager.java

TASK-1087 - Job variant-family indexing - OutOfMemoryError, although job status listed as DONE

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/rga/RgaEngine.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/rga/RgaManager.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/rga/RgaQueryParams.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/rga/RgaQueryParser.java
opencga-analysis/src/test/java/org/opencb/opencga/analysis/rga/RgaQueryParserTest.java

TASK-2386 - RGA should allow querying COMP_HET in pairs

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/MongoDBAdaptor.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/MongoDBUtils.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/IndividualManagerTest.java
pom.xml

TASK-2290 - Fix disorder filter split

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/JobManager.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/CatalogManagerTest.java
opencga-catalog/src/test/resources/configuration-test.yml
opencga-core/src/main/java/org/opencb/opencga/core/models/common/Enums.java
opencga-core/src/main/resources/configuration.yml

TASK-2437 - Operation jobs jam on duplicated operations

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/JobManager.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/CatalogManagerTest.java

TASK-2484 - Error fetching jobs to reuse with multiple studies with the same id

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/manager/VariantStorageManager.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/manager/operations/VariantStatsOperationManager.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/operations/VariantStatsIndexOperationTool.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/stats/VariantStatsAnalysis.java
opencga-analysis/src/test/java/org/opencb/opencga/analysis/variant/manager/operations/AbstractVariantOperationManagerTest.java
opencga-analysis/src/test/java/org/opencb/opencga/analysis/variant/manager/operations/PlatinumFileIndexerTest.java
opencga-analysis/src/test/java/org/opencb/opencga/analysis/variant/manager/operations/StatsVariantStorageTest.java
opencga-analysis/src/test/java/org/opencb/opencga/analysis/variant/manager/operations/VariantFileIndexerOperationManagerTest.java
opencga-analysis/src/test/java/org/opencb/opencga/analysis/variant/manager/operations/VariantImportTest.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/internal/executors/VariantInternalCommandExecutor.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/CohortManager.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/StorageEngineFactory.java

TASK-2421 - Operation 'variant-stats-index' ignores the AggregationMappingFile

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/clinical/InterpretationAnalysis.java

TASK-2387 Fix interpretation save

---

opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/utils/AbstractHBaseDataWriter.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/stats/VariantStatsMapper.java

TASK-2364 - RegionTooBusyException - StoreTooBusy - Above parallelPutToStoreThreadLimit(10)

---

opencga-analysis/src/test/java/org/opencb/opencga/analysis/variant/manager/VariantCatalogQueryUtilsTest.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/query/VariantQueryUtils.java

TASK-2014 - Panel intersection between panel and single position regions (chr:pos) not working

TASK-2014 - Panel intersection between panel and single position regions (chr:pos) not working

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/InterpretationManager.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/InterpretationManagerTest.java

TASK-2418 - Interpretation create forces to contain all panels

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/wrappers/exomiser/ExomiserWrapperAnalysisExecutor.java

Fix sample file when executing Exomiser for familes

TASK-2316 Fix sample file when executing Exomiser with families

---

opencga-server/src/main/java/org/opencb/opencga/server/rest/CohortWSServer.java

TASK-2357 - Cohort Browser error when trying to filter by more than one cohort type

---

opencga-app/src/main/java/org/opencb/opencga/app/cli/admin/executors/CatalogCommandExecutor.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/DBAdaptorFactory.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/MetaMongoDBAdaptor.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/MongoDBAdaptorFactory.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/ProjectMongoDBAdaptor.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/CatalogManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/FileManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/templates/TemplateManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/utils/CatalogDemo.java
opencga-catalog/src/main/resources/catalog-indexes.txt
opencga-catalog/src/test/java/org/opencb/opencga/catalog/auth/authorization/CatalogAuthorizationManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/db/mongodb/MetaMongoDBAdaptorTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/db/mongodb/MongoDBAdaptorTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/db/mongodb/ProjectMongoDBAdaptorTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/CatalogManagerExternalResource.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/ClinicalAnalysisManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/FamilyManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/FileManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/PanelManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/SampleManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/utils/CatalogFileUtilsTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/utils/CatalogSampleAnnotationsLoaderTest.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/admin/AdminWSServer.java

TASK-2297 - Upgrade MongoDB version to 5.0.14

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/alignment/AlignmentStorageManager.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/clinical/ClinicalInterpretationManager.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/manager/VariantStorageManager.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/manager/operations/VariantAnnotationOperationManager.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/manager/operations/VariantFileIndexerOperationManager.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/metadata/CatalogStorageMetadataSynchronizer.java
opencga-analysis/src/test/java/org/opencb/opencga/analysis/variant/manager/VariantCatalogQueryUtilsTest.java
opencga-app/src/main/java/org/opencb/opencga/app/migrations/v2_6_0/storage/AddCellbaseDataRelease.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/ProjectManager.java
opencga-core/src/main/java/org/opencb/opencga/core/api/ParamConstants.java
opencga-core/src/main/java/org/opencb/opencga/core/config/storage/CellBaseConfiguration.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/metadata/VariantStorageMetadataManager.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/metadata/models/ProjectMetadata.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/utils/CellBaseUtils.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/VariantStorageEngine.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/DefaultVariantAnnotationManager.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/VariantAnnotationManager.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/annotators/AbstractCellBaseVariantAnnotator.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/annotators/CellBaseRestVariantAnnotator.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/annotators/VariantAnnotator.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/annotators/VariantAnnotatorFactory.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/annotators/VepVariantAnnotator.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/search/solr/VariantSearchManager.java
opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/utils/CellBaseUtilsTest.java
opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/variant/annotation/DummyTestAnnotator.java
opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/variant/annotation/VariantAnnotationManagerTest.java
opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/variant/query/VariantQueryParserTest.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/HadoopVariantStorageTest.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/index/family/FamilyIndexTest.java

Use dataRelease from Cellbase in OpenCGA

TASK-1201 - Use dataRelease from Cellbase in OpenCGA

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/SampleMongoDBAdaptor.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/SampleManagerTest.java

TASK-2539 - Sample and Individual not properly associated

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/alignment/AlignmentStorageManager.java
opencga-analysis/src/test/java/org/opencb/opencga/analysis/alignment/AlignmentAnalysisTest.java

Fix gene coverage stats analysis

TASK-3813 Fix gene coverage stats analysis when using CellBase data release

---

opencga-app/src/main/java/org/opencb/opencga/app/migrations/v2_6_0/storage/AddCellbaseDataRelease.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/auth/authorization/CatalogAuthorizationManager.java

TASK-3796 - Migration 'add_cellbase_data_release' failed with message: Error executing operation configureCellbase

TASK-3796 - Migration 'add_cellbase_data_release' failed with message: Error executing operation configureCellbase

---

opencga-core/src/main/java/org/opencb/opencga/core/common/IOUtils.java
opencga-core/src/main/resources/configuration.yml
opencga-master/src/main/java/org/opencb/opencga/master/monitor/executors/K8SExecutor.java

TASK-1574 - Unexpected "Killed" job at Kubernetes

TASK-1574 - Unexpected "Killed" job at Kubernetes

---

opencga-app/app/cloud/docker/compose/conf/configuration.yml
opencga-catalog/src/main/java/org/opencb/opencga/catalog/auth/authorization/AuthorizationManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/auth/authorization/CatalogAuthorizationManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/UserManager.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/auth/authorization/CatalogAuthorizationManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/AbstractManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/CatalogManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/ClinicalAnalysisManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/FamilyManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/FileManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/InterpretationManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/PanelManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/ProjectManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/SampleManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/StudyManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/utils/CatalogFileUtilsTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/utils/FileMetadataReaderTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/utils/FileScannerTest.java
opencga-catalog/src/test/resources/configuration-test.yml
opencga-core/src/main/java/org/opencb/opencga/core/config/Configuration.java
opencga-core/src/main/resources/configuration.yml
opencga-core/src/test/resources/configuration-test.yml
opencga-server/src/main/java/org/opencb/opencga/server/rest/UserWSServer.java

TASK-2551 - Remove /user/create webservice

---

.github/workflows/docker-tools.yml
.github/workflows/release.yml

TASK-3874 - Releases are not naming the opencga-ext-tools properly

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/ProjectMongoDBAdaptor.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/utils/FqnUtils.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/ProjectManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/utils/FqnUtilsTest.java

TASK-3908 - Unable to search for shared projects

TASK-3908 - Unable to search for shared projects

---

opencga-app/src/main/java/org/opencb/opencga/app/cli/CommandExecutor.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/internal/executors/ClinicalCommandExecutor.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/internal/executors/CohortCommandExecutor.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/internal/executors/FamilyCommandExecutor.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/internal/executors/FileCommandExecutor.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/internal/executors/IndividualCommandExecutor.java
opencga-app/src/main/java/org/opencb/opencga/app/cli/internal/executors/SampleCommandExecutor.java

TASK-3897 - Error executing exomiser with custom workspace dir

TASK-3897 - Error executing exomiser with custom workspace dir

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/ClinicalAnalysisMongoDBAdaptor.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/ClinicalAnalysisManagerTest.java

TASK-4074 - Field attributes in Clinical analysis is not set with update

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/manager/VariantCatalogQueryUtils.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/metadata/models/Trio.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/VariantStorageEngine.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/query/executors/CompoundHeterozygousQueryExecutor.java
opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/variant/query/executors/CompoundHeterozygousQueryExecutorTest.java

TASK-4117 - Variant query error by Compount Het

TASK-4117 - Variant query error by Compount Het

---

opencga-analysis/src/test/java/org/opencb/opencga/analysis/family/FamilyAnalysisTest.java
opencga-app/app/analysis/pedigree-graph/ped.R
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/CatalogManagerExternalResource.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/ClinicalAnalysisManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/DummyModelUtils.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/FamilyManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/IndividualManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/SampleManagerTest.java

Fix Junit tests related to families when creating the pedigree graph.

 TASK-4204 CI/CD opencga errors when running Junit tests related to families.

---

opencga-catalog/src/test/java/org/opencb/opencga/templates/TemplateManagerTest.java

Skip test from TemplateManagerTest

TASK-4204 CI/CD opencga errors when running Junit tests related to families.

---

opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/search/VariantSearchToVariantConverter.java
opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/variant/search/VariantSearchToVariantConverterTest.java

TASK-4213 - Fix variant search to variant converter

TASK-4213 - Fix variant search to variant converter

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/migration/MigrationManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/migration/MigrationRun.java

TASK-4215 - Cannot initialise CatalogManager

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/FamilyMongoDBAdaptor.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/MongoDBAdaptor.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/StudyMongoDBAdaptor.java
opencga-catalog/src/test/java/org/opencb/opencga/templates/TemplateManagerTest.java
opencga-core/src/main/java/org/opencb/opencga/core/common/JacksonUtils.java

TASK-4204 - CI/CD opencga errors when running Junit tests related to families.

TASK-4204 - CI/CD opencga errors when running Junit tests related to families.

---

opencga-core/src/main/java/org/opencb/opencga/core/models/variant/GwasAnalysisParams.java

TASK-4285 - GWAS cannot be executed

---

.github/workflows/task.yml
opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/MetaMongoDBAdaptor.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/iterators/ClinicalAnalysisCatalogMongoDBIterator.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/ClinicalAnalysisManagerTest.java

TASK-4143 - Migration error: Issue in ClinicalMongoDBIterator

---

.github/workflows/develop.yml
opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/manager/VariantStorageManager.java
opencga-app/src/main/java/org/opencb/opencga/app/migrations/v2_1_0/storage/AddCellbaseConfigurationToProject.java
opencga-app/src/main/java/org/opencb/opencga/app/migrations/v2_6_0/storage/AddCellbaseDataRelease.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/ProjectManager.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/CatalogManagerTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/ProjectManagerTest.java
opencga-core/src/main/java/org/opencb/opencga/core/cellbase/CellBaseValidator.java
opencga-core/src/test/java/org/opencb/opencga/core/cellbase/CellBaseValidatorTest.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/utils/CellBaseUtils.java
opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/annotators/CellBaseRestVariantAnnotator.java
opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/utils/CellBaseUtilsTest.java
opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/variant/annotation/VariantAnnotationManagerTest.java

TASK-4007 - Empty CellBase datarelease after project creation - variant-annotation-index fails

TASK-4007 - Empty CellBase datarelease after project creation - variant-annotation-index fails

---

opencga-app/src/main/java/org/opencb/opencga/app/cli/GeneralCliOptions.java
opencga-core/src/main/java/org/opencb/opencga/core/api/ParamConstants.java
opencga-master/src/main/java/org/opencb/opencga/master/monitor/daemons/ExecutionDaemon.java

TASK-4268 - Unable to execute jobs, "--token" param not found

TASK-4268 - Unable to execute jobs, "--token" param not found

---

opencga-catalog/src/test/java/org/opencb/opencga/templates/TemplateManagerTest.java

TASK-4376 - CICD: errors in TemplateManagerTest

TASK-4376 - CICD: errors in TemplateManagerTest

---

opencga-app/app/cloud/docker/opencga-base/Dockerfile

TASK-4099 - Deprecate opencga-init container

TASK-4099 - Deprecate opencga-init container

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/manager/VariantStorageManager.java
opencga-analysis/src/test/java/org/opencb/opencga/analysis/variant/VariantAnalysisTest.java
opencga-analysis/src/test/java/org/opencb/opencga/analysis/variant/manager/VariantOperationsTest.java

TASK-4488 - Unable to run variant-export with storage.mode = read_only

TASK-4488 - Unable to run variant-export with storage.mode = read_only

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/clinical/ClinicalInterpretationManager.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/clinical/ClinicalUtils.java
opencga-analysis/src/main/java/org/opencb/opencga/analysis/clinical/exomiser/ExomiserClinicalVariantCreator.java
opencga-analysis/src/test/java/org/opencb/opencga/analysis/clinical/ClinicalUtilsTest.java

Fix clinical variant query with the paremeter includeInterpretation

TASK-4450 Exomiser details tab in the Sample Variant Browser doesn't show the results from Exomiser

---

opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/metadata/VariantStorageMetadataManager.java
opencga-storage/opencga-storage-core/src/test/resources/variant-large-sv.vcf
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/HadoopLocalLoadVariantStoragePipeline.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/HadoopVariantStorageOptions.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/query/LocusQuery.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/query/SampleIndexQuery.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/query/SingleSampleIndexQuery.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/AbstractSampleIndexEntryFilter.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexDBAdaptor.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexDriver.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexQueryParser.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexSchema.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/mr/SampleIndexTableRecordReader.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/VariantHadoopDBWriterTest.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexDBAdaptorTest.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexEntryFilterTest.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexQueryParserTest.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/test/java/org/opencb/opencga/storage/hadoop/variant/index/sample/SampleIndexTest.java

Filtering by gene/region not working for CNVs in sample variant browser

TASK-4146 - Filtering by gene/region not working for CNVs in sample variant browser

---

opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/HadoopLocalLoadVariantStoragePipeline.java

TASK-4736 - Error executing junit "VariantHadoopDBWriterTest.loadVariantsBasic"

TASK-4736 - Error executing junit "VariantHadoopDBWriterTest.loadVariantsBasic"

---

opencga-app/pom.xml
opencga-core/pom.xml
opencga-core/src/main/java/org/opencb/opencga/core/common/GitRepositoryState.java

TASK-4688 - Avoid git.properties collision

TASK-4688 - Avoid git.properties collision

---

opencga-server/src/main/java/org/opencb/opencga/server/OpenCGAHealthCheckMonitor.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/MetaWSServer.java
opencga-server/src/main/java/org/opencb/opencga/server/rest/OpenCGAWSServer.java

TASK-4945 - OpenCGA Status not being updated

TASK-4945 - OpenCGA Status not being updated

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/IndividualMongoDBAdaptor.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/SampleMongoDBAdaptor.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/FamilyManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/IndividualManager.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/SampleManager.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/SampleManagerTest.java

TASK-4210 - Catalog delete operations may not check if data is used in Clinical Analyses

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/mutationalSignature/MutationalSignatureLocalAnalysisExecutor.java
opencga-app/app/cloud/docker/opencga-ext-tools/Dockerfile

TASK-5038 Update signature.tools.lib package to fix fitting and HRDetect analysis

---

opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/SampleManagerTest.java

TASK-5083 - Sample - Case junit test not working

---

opencga-app/src/main/java/org/opencb/opencga/app/cli/main/io/TextOutputWriter.java

TASK-5166 - The CLI upload service does not display error messages.

TASK-5166 - The CLI upload service does not display error messages.

---

opencga-core/src/main/java/org/opencb/opencga/core/models/clinical/ClinicalAnalysis.java
opencga-core/src/main/java/org/opencb/opencga/core/models/clinical/ClinicalAnalysisCreateParams.java
opencga-core/src/main/java/org/opencb/opencga/core/models/clinical/ClinicalAnalysisUpdateParams.java

TASK-5373 - Error compiling opencga-enterprise - ClinicalAnalyst changes

---

opencga-app/app/cloud/docker/opencga-ext-tools/Dockerfile

TASK-5450 Update signature.tools.lib package to fix HRDetect analysis

---

pom.xml

TASK-5404 - There are two implementations of SLF4J and log lines appear at the beginning of the result of each CLI command

TASK-5404 - There are two implementations of SLF4J and log lines appear at the beginning of the result of each CLI command

---

opencga-app/pom.xml
opencga-server/pom.xml
opencga-server/src/test/java/org/opencb/opencga/server/rest/ProjectWSServerTest.java
opencga-server/src/test/java/org/opencb/opencga/server/rest/UserWSServerTest.java
opencga-server/src/test/java/org/opencb/opencga/server/rest/VariableSetWSServerTest.java
pom.xml

TASK-4437 - Update general dependencies from dependabot (security alerts)

TASK-4437 - Update general dependencies from dependabot (security alerts)

---

opencga-analysis/pom.xml
opencga-app/pom.xml
opencga-catalog/pom.xml
opencga-client/pom.xml
opencga-clinical/pom.xml
opencga-core/pom.xml
opencga-master/pom.xml
opencga-server/pom.xml
opencga-storage/opencga-storage-app/pom.xml
opencga-storage/opencga-storage-benchmark/pom.xml
opencga-storage/opencga-storage-core/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-deps/opencga-storage-hadoop-deps-emr6.1/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-deps/opencga-storage-hadoop-deps-hdp2.6/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-deps/opencga-storage-hadoop-deps-hdp3.1/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-deps/pom.xml
opencga-storage/opencga-storage-hadoop/pom.xml
opencga-storage/opencga-storage-server/pom.xml
opencga-storage/pom.xml
opencga-test/pom.xml
pom.xml

TASK-5444 - Fix OpenCB repository versions to conform to XetaBase 2.0.0 version

TASK-5444 - Fix OpenCB repository versions to conform to XetaBase 2.0.0 version

---

opencga-app/src/main/java/org/opencb/opencga/app/cli/CommandExecutor.java

TASK-5511 - opencga.sh CLI option --json-data-model produces malformed JSON

TASK-5511 - opencga.sh CLI option --json-data-model produces malformed JSON

---

opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/metadata/CatalogVariantMetadataFactory.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/converters/AnnotationConverter.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/utils/AnnotationUtils.java
opencga-catalog/src/main/java/org/opencb/opencga/catalog/utils/CatalogSampleAnnotationsLoader.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/utils/CatalogAnnotationsValidatorTest.java
opencga-catalog/src/test/java/org/opencb/opencga/catalog/utils/CatalogSampleAnnotationsLoaderTest.java
opencga-core/src/main/java/org/opencb/opencga/core/models/common/AnnotationSet.java
opencga-core/src/main/java/org/opencb/opencga/core/models/study/Variable.java
pom.xml

TASK-1294 - Remove deprecated VariableSet fields

---

opencga-catalog/src/test/resources/templates/manifest.yml
opencga-catalog/src/test/resources/templates_yaml/manifest.yml

TASK-5609 - Can't merge into develop (v3.0.0)

---

opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/ClinicalAnalysisManager.java

 TASK-5622 Fix Junit test (assert fails)

---

opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/VariantAnnotationManager.java
opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/variant/annotation/VariantAnnotationManagerTest.java

TASK-5493 - Error in variant-index-annotation : "Private sources has changed"

TASK-5493 - Error in variant-index-annotation : "Private sources has changed"

---

opencga-analysis/pom.xml

[TASK-6082](https://app.clickup.com/t/36631768/TASK-6082)

TASK-6082 - Fix pom.xml to include the src/test/resources folder

---

opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/query/projection/VariantQueryProjectionParser.java
opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/variant/adaptors/VariantDBAdaptorMultiFileTest.java
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/index/SampleIndexOnlyVariantQueryExecutor.java

OpenCGA-Storage test failed on release-2.12.x branch

TASK-6436 - OpenCGA-Storage test failed on release-2.12.x branch

---

opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/search/solr/SolrQueryParser.java

[TASK-6492](https://app.clickup.com/t/36631768/TASK-6492)

TASK-6492 Clinical Case query failed with cvCt value loss_of_function

---

pom.xml

TASK-6835 - Cellbase dependency error in opencga build

TASK-6835 - Cellbase dependency error in opencga build

---

.github/workflows/pull-request-approved.yml
.github/workflows/scripts/get-xetabase-branch.sh
opencga-analysis/pom.xml
opencga-app/pom.xml
opencga-catalog/pom.xml
opencga-client/pom.xml
opencga-clinical/pom.xml
opencga-core/pom.xml
opencga-master/pom.xml
opencga-server/pom.xml
opencga-storage/opencga-storage-app/pom.xml
opencga-storage/opencga-storage-benchmark/pom.xml
opencga-storage/opencga-storage-core/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-compat/opencga-storage-hadoop-compat-api/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-compat/opencga-storage-hadoop-compat-hbase2.0/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-compat/opencga-storage-hadoop-compat-hbase2.2/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-compat/opencga-storage-hadoop-compat-hbase2.4/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-compat/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-lib/opencga-storage-hadoop-lib-emr6.1/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-lib/opencga-storage-hadoop-lib-emr6.13/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-lib/opencga-storage-hadoop-lib-hdi5.1/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-lib/opencga-storage-hadoop-lib-hdp3.1/pom.xml
opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-lib/pom.xml
opencga-storage/opencga-storage-hadoop/pom.xml
opencga-storage/opencga-storage-server/pom.xml
opencga-storage/pom.xml
opencga-test/pom.xml
pom.xml

TASK-6879 - Adapt GitHub Actions, CICD workflows and release scripts to new SDLC

TASK-6879 - Adapt GitHub Actions, CICD workflows and release scripts to new SDLC

---

opencga-core/src/main/resources/configuration.yml

TASK-6458 - Deployment: Xetabase kubernetes 1.29 compatibility

---

opencga-storage/opencga-storage-core/src/test/java/org/opencb/opencga/storage/core/variant/search/VariantSearchTest.java

[TASK-7439](https://app.clickup.com/t/8697r1j3u)

TASK-7439 - Variant Browsers shows a VariantQueryException when running aggregation stats

---

.github/workflows/check-junit-test.yml
.github/workflows/develop.yml
.github/workflows/manual-deploy-docker.yml
.github/workflows/manual-deploy-ext-tools.yml
.github/workflows/manual-deploy-python-notebook.yml
.github/workflows/pull-request-approved.yml
.github/workflows/reusable-delete-docker.yml
.github/workflows/test-analysis.yml
opencga-app/app/cloud/docker/opencga-workflow/Dockerfile

[TASK-7693-rel - Upgrade Ubuntu image on GitHub Actions](https://app.clickup.com/t/36631768/TASK-7693-rel)

TASK-7693-rel - Upgrade Ubuntu image on GitHub Actions

---

.github/workflows/check-junit-test.yml
.github/workflows/develop.yml
.github/workflows/manual-deploy-docker.yml
.github/workflows/manual-deploy-ext-tools.yml
.github/workflows/manual-deploy-python-notebook.yml
.github/workflows/pull-request-approved.yml
.github/workflows/reusable-delete-docker.yml
.github/workflows/test-analysis.yml
opencga-app/app/cloud/docker/opencga-workflow/Dockerfile

[TASK-7693-dev - Upgrade Ubuntu image on GitHub Actions](https://app.clickup.com/t/36631768/TASK-7693-dev)

TASK-7693-dev - Upgrade Ubuntu image on GitHub Actions
